---
- hosts: backend
  remote_user: ubuntu
  become: yes
  connection: ssh
  roles:
    - backend-role

- hosts: frontend
  remote_user: ubuntu
  become: yes
  connection: ssh
  roles:
    - frontend-role
