---
- name: First update the packagers
  apt: update_cache=yes force_apt_get=yes

- name: Install python3-pip, python3-dev and git
  apt: name='{{item}}' state=present
  with_items:
    - python3-pip
    - python3-dev
    - git

- name: Installing virtualenv using pip3
  pip:
    name: virtualenv
    executable: pip3

- name: cloning project from git
  git:
   repo: https://github.com/peyyala7hills/new_chatapp
   dest: /home/ubuntu/new_chatapp
   clone: yes

- name: creating virtual environment inside new_chatapp
  command:
    cmd: virtualenv /home/ubuntu/new_chatapp/venv
    creates: /home/ubuntu/new_chatapp/venv

- name: Installing requirements.txt in virtualenv
  pip:
    requirements: /home/ubuntu/new_chatapp/requirements.txt
    virtualenv: /home/ubuntu/new_chatapp/venv
    virtualenv_python: python3

# - name: Installing gunicorn
#   pip:
#     name: gunicorn
#     executable: pip3

- name: installing mysql-server
  apt: name=mysql-server state=present

- name: intalling mysql-client
  apt: name=mysql-client state=present

- name: Start the MySQL service
  action: service name=mysql state=started

- name: Installing PyMySql
  pip:
    name: pymysql
    executable: pip3

#- name: Create user
#  mysql_user:
#    name: root
#    password: mysql1234
#    login_host: localhost
#- name: Creating new mysql user
#- mysql_user:
#  name: root
#    password: mysql1234
#    login_host: localhost
#    login_user: root
#    login_password: mysql1234

- name: creating chat_db database
  mysql_db:
    name: chat_db
    login_host: localhost
    login_user: root
    login_password: mysql1234

- name: editing settings.py file to change db configs
  blockinfile:
    path: /home/ubuntu/new_chatapp/fundoo/fundoo/settings.py
    marker_begin: "    'default': {"
    marker_end: "    }"
    block: |-
      "      'ENGINE': 'django.db.backends.mysql'",
      "      'NAME': 'chat_db'",
      "      'USER': 'root'",
      "      'PASSWORD': 'mysql1234'",
      "      'HOST': 'localhost'",
      "      'PORT': '3306'",

- name: install default-libmysqlclient-dev package for chat app
  apt: name=default-libmysqlclient-dev state=present

- name: install libssl-dev package for chat app
  apt: name=libssl-dev state=present

- name: install mysqlclient
  pip:
    name: mysqlclient
    virtualenv: /home/ubuntu/new_chatapp/venv

- name: install package for chat app
  apt: name=python3-psycopg2 state=present

- name: install psycopg2-binary
  pip:
    name: psycopg2-binary
    virtualenv: /home/ubuntu/new_chatapp/venv
    virtualenv_python: python3


- name: running python migrate
  django_manage:
    command:  migrate
    app_path: /home/ubuntu/new_chatapp/fundoo
    virtualenv: /home/ubuntu/new_chatapp/venv

- name: running python makemigration
  django_manage:
    command:  makemigrations
    app_path: /home/ubuntu/new_chatapp/fundoo
    virtualenv: /home/ubuntu/new_chatapp/venv

- name: creating gunicorn.service file
  file:
    path: /etc/systemd/system/gunicorn.service
    state: touch

- name: copying gunicorn template to gunicorn.service file
  template:
    src: gunicorn.j2
    dest: /etc/systemd/system/gunicorn.service

- name: starting and enabling  gunicorn
  service:
    name: gunicorn
    enabled: true
    daemon-reload: yes
    state: started
